version: "3.9"

services:
  db:
    image: mysql
    ports:
      - 3308:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - prod.env
    volumes:
      - ./mysql-data:/var/lib/mysql
